// Editable portfolio data for the CamApp Digital logo-design landing page.
// Update this file when adding, removing, reordering, or replacing portfolio projects.
window.camappPortfolioData = {
  "categories": [
    {
      "id": "food",
      "labelEn": "Food & Beverage",
      "labelKm": "អាហារ និងភេសជ្ជៈ"
    },
    {
      "id": "beauty",
      "labelEn": "Beauty & Fashion",
      "labelKm": "សម្រស់ និងម៉ូដ"
    },
    {
      "id": "real-estate",
      "labelEn": "Real Estate",
      "labelKm": "អចលនទ្រព្យ"
    },
    {
      "id": "healthcare",
      "labelEn": "Healthcare",
      "labelKm": "សុខភាព និងគ្លីនិក"
    },
    {
      "id": "retail",
      "labelEn": "Retail",
      "labelKm": "លក់រាយ"
    },
    {
      "id": "technology",
      "labelEn": "Technology",
      "labelKm": "បច្ចេកវិទ្យា"
    },
    {
      "id": "professional",
      "labelEn": "Professional Services",
      "labelKm": "សេវាកម្មវិជ្ជាជីវៈ"
    },
    {
      "id": "education",
      "labelEn": "Education & Nonprofit",
      "labelKm": "អប់រំ និងអង្គការមិនរកប្រាក់ចំណេញ"
    },
    {
      "id": "auto",
      "labelEn": "Auto & Vehicle",
      "labelKm": "យានយន្ត"
    },
    {
      "id": "other",
      "labelEn": "Other Logo Projects",
      "labelKm": "គម្រោងឡូហ្គោផ្សេងៗ"
    }
  ],
  "projects": [
    {
      "id": "portfolio-lavain-coffee",
      "slug": "lavain-coffee",
      "brandName": "Lavain Coffee",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/lavain-coffee/lavain-coffee-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Lavain Coffee logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Lavain Coffee",
      "descriptionEn": "Logo design project for Lavain Coffee in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Lavain Coffee ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 1,
      "featured": true
    },
    {
      "id": "portfolio-skinglow-beauty-skincare",
      "slug": "skinglow-beauty-skincare",
      "brandName": "SKINGLOW BEAUTY SKINCARE",
      "businessCategory": "beauty",
      "categoryLabelEn": "Beauty & Fashion",
      "categoryLabelKm": "សម្រស់ និងម៉ូដ",
      "imagePath": "portfolio/skinglow-beauty-skincare/skinglow-beauty-skincare-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "SKINGLOW BEAUTY SKINCARE logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ SKINGLOW BEAUTY SKINCARE",
      "descriptionEn": "Logo design project for SKINGLOW BEAUTY SKINCARE in the Beauty & Fashion category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ SKINGLOW BEAUTY SKINCARE ក្នុងប្រភេទសម្រស់ និងម៉ូដ។",
      "displayOrder": 2,
      "featured": true
    },
    {
      "id": "portfolio-khmer-angkor-real-estate",
      "slug": "khmer-angkor-real-estate",
      "brandName": "Khmer Angkor Real Estate",
      "businessCategory": "real-estate",
      "categoryLabelEn": "Real Estate",
      "categoryLabelKm": "អចលនទ្រព្យ",
      "imagePath": "portfolio/khmer-angkor-real-estate/khmer-angkor-real-estate-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Khmer Angkor Real Estate logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Khmer Angkor Real Estate",
      "descriptionEn": "Logo design project for Khmer Angkor Real Estate in the Real Estate category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Khmer Angkor Real Estate ក្នុងប្រភេទអចលនទ្រព្យ។",
      "displayOrder": 3,
      "featured": true
    },
    {
      "id": "portfolio-jd-law-firm",
      "slug": "jd-law-firm",
      "brandName": "JD LAW Firm",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/jd-law-firm/jd-law-firm-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1600,
      "altTextEn": "JD LAW Firm logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ JD LAW Firm",
      "descriptionEn": "Logo design project for JD LAW Firm in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ JD LAW Firm ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 4,
      "featured": true
    },
    {
      "id": "portfolio-sct-roof-tile",
      "slug": "sct-roof-tile",
      "brandName": "SCT ROOF TILE",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/sct-roof-tile/sct-roof-tile-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "SCT ROOF TILE logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ SCT ROOF TILE",
      "descriptionEn": "Logo design project for SCT ROOF TILE in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ SCT ROOF TILE ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 5,
      "featured": true
    },
    {
      "id": "portfolio-eleven-mart",
      "slug": "eleven-mart",
      "brandName": "11-Mart",
      "businessCategory": "retail",
      "categoryLabelEn": "Retail",
      "categoryLabelKm": "លក់រាយ",
      "imagePath": "portfolio/eleven-mart/eleven-mart-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "11-Mart logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ 11-Mart",
      "descriptionEn": "Logo design project for 11-Mart in the Retail category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ 11-Mart ក្នុងប្រភេទលក់រាយ។",
      "displayOrder": 6,
      "featured": true
    },
    {
      "id": "portfolio-ent",
      "slug": "ent",
      "brandName": "ENT",
      "businessCategory": "healthcare",
      "categoryLabelEn": "Healthcare",
      "categoryLabelKm": "សុខភាព និងគ្លីនិក",
      "imagePath": "portfolio/ent/ent-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "ENT logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ ENT",
      "descriptionEn": "Logo design project for ENT in the Healthcare category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ ENT ក្នុងប្រភេទសុខភាព និងគ្លីនិក។",
      "displayOrder": 7,
      "featured": true
    },
    {
      "id": "portfolio-scp-auto",
      "slug": "scp-auto",
      "brandName": "SCP Auto",
      "businessCategory": "auto",
      "categoryLabelEn": "Auto & Vehicle",
      "categoryLabelKm": "យានយន្ត",
      "imagePath": "portfolio/scp-auto/scp-auto-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1200,
      "altTextEn": "SCP Auto logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ SCP Auto",
      "descriptionEn": "Logo design project for SCP Auto in the Auto & Vehicle category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ SCP Auto ក្នុងប្រភេទយានយន្ត។",
      "displayOrder": 8,
      "featured": true
    },
    {
      "id": "portfolio-htd-furniture",
      "slug": "htd-furniture",
      "brandName": "HTD Furniture",
      "businessCategory": "retail",
      "categoryLabelEn": "Retail",
      "categoryLabelKm": "លក់រាយ",
      "imagePath": "portfolio/htd-furniture/htd-furniture-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "HTD Furniture logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ HTD Furniture",
      "descriptionEn": "Logo design project for HTD Furniture in the Retail category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ HTD Furniture ក្នុងប្រភេទលក់រាយ។",
      "displayOrder": 9,
      "featured": true
    },
    {
      "id": "portfolio-coppercraftkh",
      "slug": "coppercraftkh",
      "brandName": "Coppercraftkh",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/coppercraftkh/coppercraftkh-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Coppercraftkh logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Coppercraftkh",
      "descriptionEn": "Logo design project for Coppercraftkh in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Coppercraftkh ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 10,
      "featured": true
    },
    {
      "id": "portfolio-the-money",
      "slug": "the-money",
      "brandName": "The Money",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/the-money/the-money-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "The Money logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ The Money",
      "descriptionEn": "Logo design project for The Money in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ The Money ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 11,
      "featured": true
    },
    {
      "id": "portfolio-chili-chili",
      "slug": "chili-chili",
      "brandName": "Chili Chili",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/chili-chili/chili-chili-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Chili Chili logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Chili Chili",
      "descriptionEn": "Logo design project for Chili Chili in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Chili Chili ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 12,
      "featured": true
    },
    {
      "id": "portfolio-pes",
      "slug": "pes",
      "brandName": "PES",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/pes/pes-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1148,
      "altTextEn": "PES logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ PES",
      "descriptionEn": "Logo design project for PES in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ PES ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 13,
      "featured": false
    },
    {
      "id": "portfolio-kdam-srae",
      "slug": "kdam-srae",
      "brandName": "kdam srae",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/kdam-srae/kdam-srae-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1120,
      "altTextEn": "kdam srae logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ kdam srae",
      "descriptionEn": "Logo design project for kdam srae in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ kdam srae ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 14,
      "featured": false
    },
    {
      "id": "portfolio-clinic",
      "slug": "clinic",
      "brandName": "Clinic",
      "businessCategory": "healthcare",
      "categoryLabelEn": "Healthcare",
      "categoryLabelKm": "សុខភាព និងគ្លីនិក",
      "imagePath": "portfolio/clinic/clinic-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Clinic logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Clinic",
      "descriptionEn": "Logo design project for Clinic in the Healthcare category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Clinic ក្នុងប្រភេទសុខភាព និងគ្លីនិក។",
      "displayOrder": 15,
      "featured": false
    },
    {
      "id": "portfolio-nay-houy-wholesale",
      "slug": "nay-houy-wholesale",
      "brandName": "Nay Houy Wholesale",
      "businessCategory": "retail",
      "categoryLabelEn": "Retail",
      "categoryLabelKm": "លក់រាយ",
      "imagePath": "portfolio/nay-houy-wholesale/nay-houy-wholesale-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Nay Houy Wholesale logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Nay Houy Wholesale",
      "descriptionEn": "Logo design project for Nay Houy Wholesale in the Retail category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Nay Houy Wholesale ក្នុងប្រភេទលក់រាយ។",
      "displayOrder": 16,
      "featured": false
    },
    {
      "id": "portfolio-park-ramen",
      "slug": "park-ramen",
      "brandName": "Park Ramen",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/park-ramen/park-ramen-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1141,
      "altTextEn": "Park Ramen logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Park Ramen",
      "descriptionEn": "Logo design project for Park Ramen in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Park Ramen ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 17,
      "featured": false
    },
    {
      "id": "portfolio-madame",
      "slug": "madame",
      "brandName": "Madame",
      "businessCategory": "beauty",
      "categoryLabelEn": "Beauty & Fashion",
      "categoryLabelKm": "សម្រស់ និងម៉ូដ",
      "imagePath": "portfolio/madame/madame-portfolio.png",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Madame logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Madame",
      "descriptionEn": "Logo design project for Madame in the Beauty & Fashion category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Madame ក្នុងប្រភេទសម្រស់ និងម៉ូដ។",
      "displayOrder": 18,
      "featured": false
    },
    {
      "id": "portfolio-clmu",
      "slug": "clmu",
      "brandName": "CLMU CO.,Ltd",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/clmu/clmu-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1141,
      "altTextEn": "CLMU CO.,Ltd logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ CLMU CO.,Ltd",
      "descriptionEn": "Logo design project for CLMU CO.,Ltd in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ CLMU CO.,Ltd ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 19,
      "featured": false
    },
    {
      "id": "portfolio-wine-and-liquor",
      "slug": "wine-and-liquor",
      "brandName": "Wine and Liquor",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/wine-and-liquor/wine-and-liquor-portfolio.png",
      "imageWidth": 1600,
      "imageHeight": 1600,
      "altTextEn": "Wine and Liquor logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Wine and Liquor",
      "descriptionEn": "Logo design project for Wine and Liquor in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Wine and Liquor ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 20,
      "featured": false
    },
    {
      "id": "portfolio-rkk",
      "slug": "rkk",
      "brandName": "RKK",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/rkk/rkk-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "RKK logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ RKK",
      "descriptionEn": "Logo design project for RKK.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ RKK។",
      "displayOrder": 21,
      "featured": false
    },
    {
      "id": "portfolio-king-bee",
      "slug": "king-bee",
      "brandName": "King Bee",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/king-bee/king-bee-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1142,
      "altTextEn": "King Bee logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ King Bee",
      "descriptionEn": "Logo design project for King Bee.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ King Bee។",
      "displayOrder": 22,
      "featured": false
    },
    {
      "id": "portfolio-triple-s-design",
      "slug": "triple-s-design",
      "brandName": "TripleS Design",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/triple-s-design/triple-s-design-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "TripleS Design logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ TripleS Design",
      "descriptionEn": "Logo design project for TripleS Design in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ TripleS Design ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 23,
      "featured": false
    },
    {
      "id": "portfolio-danin-electric-shop",
      "slug": "danin-electric-shop",
      "brandName": "Danin electric shop",
      "businessCategory": "technology",
      "categoryLabelEn": "Technology",
      "categoryLabelKm": "បច្ចេកវិទ្យា",
      "imagePath": "portfolio/danin-electric-shop/danin-electric-shop-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Danin electric shop logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Danin electric shop",
      "descriptionEn": "Logo design project for Danin electric shop in the Technology category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Danin electric shop ក្នុងប្រភេទបច្ចេកវិទ្យា។",
      "displayOrder": 24,
      "featured": false
    },
    {
      "id": "portfolio-tos-nham",
      "slug": "tos-nham",
      "brandName": "តោះញាំ",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/tos-nham/tos-nham-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "តោះញាំ logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ តោះញាំ",
      "descriptionEn": "Logo design project for តោះញាំ in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ តោះញាំ ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 25,
      "featured": false
    },
    {
      "id": "portfolio-sopheak",
      "slug": "sopheak",
      "brandName": "Sopheak",
      "businessCategory": "auto",
      "categoryLabelEn": "Auto & Vehicle",
      "categoryLabelKm": "យានយន្ត",
      "imagePath": "portfolio/sopheak/sopheak-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Sopheak logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Sopheak",
      "descriptionEn": "Logo design project for Sopheak in the Auto & Vehicle category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Sopheak ក្នុងប្រភេទយានយន្ត។",
      "displayOrder": 26,
      "featured": false
    },
    {
      "id": "portfolio-luna-coffee",
      "slug": "luna-coffee",
      "brandName": "Luna Coffee",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/luna-coffee/luna-coffee-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Luna Coffee logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Luna Coffee",
      "descriptionEn": "Logo design project for Luna Coffee in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Luna Coffee ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 27,
      "featured": false
    },
    {
      "id": "portfolio-365-property",
      "slug": "365-property",
      "brandName": "365 Property",
      "businessCategory": "real-estate",
      "categoryLabelEn": "Real Estate",
      "categoryLabelKm": "អចលនទ្រព្យ",
      "imagePath": "portfolio/365-property/365-property-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "365 Property logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ 365 Property",
      "descriptionEn": "Logo design project for 365 Property in the Real Estate category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ 365 Property ក្នុងប្រភេទអចលនទ្រព្យ។",
      "displayOrder": 28,
      "featured": false
    },
    {
      "id": "portfolio-rcs-auto",
      "slug": "rcs-auto",
      "brandName": "RCS Auto",
      "businessCategory": "auto",
      "categoryLabelEn": "Auto & Vehicle",
      "categoryLabelKm": "យានយន្ត",
      "imagePath": "portfolio/rcs-auto/rcs-auto-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "RCS Auto logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ RCS Auto",
      "descriptionEn": "Logo design project for RCS Auto in the Auto & Vehicle category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ RCS Auto ក្នុងប្រភេទយានយន្ត។",
      "displayOrder": 29,
      "featured": false
    },
    {
      "id": "portfolio-foundation-charity",
      "slug": "foundation-charity",
      "brandName": "Foundation Charity",
      "businessCategory": "education",
      "categoryLabelEn": "Education & Nonprofit",
      "categoryLabelKm": "អប់រំ និងអង្គការមិនរកប្រាក់ចំណេញ",
      "imagePath": "portfolio/foundation-charity/foundation-charity-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1333,
      "altTextEn": "Foundation Charity logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Foundation Charity",
      "descriptionEn": "Logo design project for Foundation Charity in the Education & Nonprofit category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Foundation Charity ក្នុងប្រភេទអប់រំ និងអង្គការមិនរកប្រាក់ចំណេញ។",
      "displayOrder": 30,
      "featured": false
    },
    {
      "id": "portfolio-jasons-mart",
      "slug": "jasons-mart",
      "brandName": "Jason's Mart",
      "businessCategory": "retail",
      "categoryLabelEn": "Retail",
      "categoryLabelKm": "លក់រាយ",
      "imagePath": "portfolio/jasons-mart/jasons-mart-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Jason's Mart logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Jason's Mart",
      "descriptionEn": "Logo design project for Jason's Mart in the Retail category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Jason's Mart ក្នុងប្រភេទលក់រាយ។",
      "displayOrder": 31,
      "featured": false
    },
    {
      "id": "portfolio-moskiki",
      "slug": "moskiki",
      "brandName": "Moskiki",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/moskiki/moskiki-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1333,
      "altTextEn": "Moskiki logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Moskiki",
      "descriptionEn": "Logo design project for Moskiki.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Moskiki។",
      "displayOrder": 32,
      "featured": false
    },
    {
      "id": "portfolio-h-coffee",
      "slug": "h-coffee",
      "brandName": "H Coffee",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/h-coffee/h-coffee-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "H Coffee logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ H Coffee",
      "descriptionEn": "Logo design project for H Coffee in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ H Coffee ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 33,
      "featured": false
    },
    {
      "id": "portfolio-sovann-sethak",
      "slug": "sovann-sethak",
      "brandName": "Sovann Sethak",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/sovann-sethak/sovann-sethak-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Sovann Sethak logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Sovann Sethak",
      "descriptionEn": "Logo design project for Sovann Sethak.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Sovann Sethak។",
      "displayOrder": 34,
      "featured": false
    },
    {
      "id": "portfolio-green-action",
      "slug": "green-action",
      "brandName": "Green Action",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/green-action/green-action-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Green Action logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Green Action",
      "descriptionEn": "Logo design project for Green Action.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Green Action។",
      "displayOrder": 35,
      "featured": false
    },
    {
      "id": "portfolio-trapeang-russei-high-school",
      "slug": "trapeang-russei-high-school",
      "brandName": "វិទ្យាល័យ ត្រពាំឫស្សី",
      "businessCategory": "education",
      "categoryLabelEn": "Education & Nonprofit",
      "categoryLabelKm": "អប់រំ និងអង្គការមិនរកប្រាក់ចំណេញ",
      "imagePath": "portfolio/trapeang-russei-high-school/trapeang-russei-high-school-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "វិទ្យាល័យ ត្រពាំឫស្សី logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ វិទ្យាល័យ ត្រពាំឫស្សី",
      "descriptionEn": "Logo design project for វិទ្យាល័យ ត្រពាំឫស្សី in the Education & Nonprofit category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ វិទ្យាល័យ ត្រពាំឫស្សី ក្នុងប្រភេទអប់រំ និងអង្គការមិនរកប្រាក់ចំណេញ។",
      "displayOrder": 36,
      "featured": false
    },
    {
      "id": "portfolio-lykimhak-trading",
      "slug": "lykimhak-trading",
      "brandName": "Lykimhak trading",
      "businessCategory": "retail",
      "categoryLabelEn": "Retail",
      "categoryLabelKm": "លក់រាយ",
      "imagePath": "portfolio/lykimhak-trading/lykimhak-trading-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Lykimhak trading logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Lykimhak trading",
      "descriptionEn": "Logo design project for Lykimhak trading in the Retail category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Lykimhak trading ក្នុងប្រភេទលក់រាយ។",
      "displayOrder": 37,
      "featured": false
    },
    {
      "id": "portfolio-sun-heng",
      "slug": "sun-heng",
      "brandName": "ស៊ុនហេង 順興",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/sun-heng/sun-heng-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1333,
      "altTextEn": "ស៊ុនហេង 順興 logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ ស៊ុនហេង 順興",
      "descriptionEn": "Logo design project for ស៊ុនហេង 順興.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ ស៊ុនហេង 順興។",
      "displayOrder": 38,
      "featured": false
    },
    {
      "id": "portfolio-boat-noodle",
      "slug": "boat-noodle",
      "brandName": "ទូក គុយទាវ",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/boat-noodle/boat-noodle-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "ទូក គុយទាវ logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ ទូក គុយទាវ",
      "descriptionEn": "Logo design project for ទូក គុយទាវ in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ ទូក គុយទាវ ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 39,
      "featured": false
    },
    {
      "id": "portfolio-m-and-l",
      "slug": "m-and-l",
      "brandName": "M&L",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/m-and-l/m-and-l-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "M&L logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ M&L",
      "descriptionEn": "Logo design project for M&L in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ M&L ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 40,
      "featured": false
    },
    {
      "id": "portfolio-fh-construction",
      "slug": "fh-construction",
      "brandName": "FH CONSTRUCTION",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/fh-construction/fh-construction-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "FH CONSTRUCTION logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ FH CONSTRUCTION",
      "descriptionEn": "Logo design project for FH CONSTRUCTION in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ FH CONSTRUCTION ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 41,
      "featured": false
    },
    {
      "id": "portfolio-kbach",
      "slug": "kbach",
      "brandName": "kbach",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/kbach/kbach-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1600,
      "altTextEn": "kbach logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ kbach",
      "descriptionEn": "Logo design project for kbach.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ kbach។",
      "displayOrder": 42,
      "featured": false
    },
    {
      "id": "portfolio-365-promotion",
      "slug": "365-promotion",
      "brandName": "365 Promotion",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/365-promotion/365-promotion-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1134,
      "altTextEn": "365 Promotion logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ 365 Promotion",
      "descriptionEn": "Logo design project for 365 Promotion in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ 365 Promotion ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 43,
      "featured": false
    },
    {
      "id": "portfolio-liya-curtain",
      "slug": "liya-curtain",
      "brandName": "លីយ៉ា វាំងនន",
      "businessCategory": "retail",
      "categoryLabelEn": "Retail",
      "categoryLabelKm": "លក់រាយ",
      "imagePath": "portfolio/liya-curtain/liya-curtain-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "លីយ៉ា វាំងនន logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ លីយ៉ា វាំងនន",
      "descriptionEn": "Logo design project for លីយ៉ា វាំងនន in the Retail category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ លីយ៉ា វាំងនន ក្នុងប្រភេទលក់រាយ។",
      "displayOrder": 44,
      "featured": false
    },
    {
      "id": "portfolio-kang-kosal",
      "slug": "kang-kosal",
      "brandName": "កងកុសល KANGKOSAL",
      "businessCategory": "other",
      "categoryLabelEn": "Other Logo Projects",
      "categoryLabelKm": "គម្រោងឡូហ្គោផ្សេងៗ",
      "imagePath": "portfolio/kang-kosal/kang-kosal-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "កងកុសល KANGKOSAL logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ កងកុសល KANGKOSAL",
      "descriptionEn": "Logo design project for កងកុសល KANGKOSAL.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ កងកុសល KANGKOSAL។",
      "displayOrder": 45,
      "featured": false
    },
    {
      "id": "portfolio-chamka-chek",
      "slug": "chamka-chek",
      "brandName": "Chamka chek",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/chamka-chek/chamka-chek-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Chamka chek logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Chamka chek",
      "descriptionEn": "Logo design project for Chamka chek in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Chamka chek ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 46,
      "featured": false
    },
    {
      "id": "portfolio-rani-chhing-breakfast",
      "slug": "rani-chhing-breakfast",
      "brandName": "រ៉ានីឈីង អាហារពេលព្រឹក",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/rani-chhing-breakfast/rani-chhing-breakfast-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "រ៉ានីឈីង អាហារពេលព្រឹក logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ រ៉ានីឈីង អាហារពេលព្រឹក",
      "descriptionEn": "Logo design project for រ៉ានីឈីង អាហារពេលព្រឹក in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ រ៉ានីឈីង អាហារពេលព្រឹក ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 47,
      "featured": false
    },
    {
      "id": "portfolio-sopheak-motorcycle-shop",
      "slug": "sopheak-motorcycle-shop",
      "brandName": "ហាងម៉ូយកង់ម៉ូតូ",
      "businessCategory": "auto",
      "categoryLabelEn": "Auto & Vehicle",
      "categoryLabelKm": "យានយន្ត",
      "imagePath": "portfolio/sopheak-motorcycle-shop/sopheak-motorcycle-shop-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "ហាងម៉ូយកង់ម៉ូតូ logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ ហាងម៉ូយកង់ម៉ូតូ",
      "descriptionEn": "Logo design project for ហាងម៉ូយកង់ម៉ូតូ in the Auto & Vehicle category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ ហាងម៉ូយកង់ម៉ូតូ ក្នុងប្រភេទយានយន្ត។",
      "displayOrder": 48,
      "featured": false
    },
    {
      "id": "portfolio-ecl",
      "slug": "ecl",
      "brandName": "ECL",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/ecl/ecl-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1158,
      "altTextEn": "ECL logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ ECL",
      "descriptionEn": "Logo design project for ECL in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ ECL ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 49,
      "featured": false
    },
    {
      "id": "portfolio-hr-creative",
      "slug": "hr-creative",
      "brandName": "HR Creative",
      "businessCategory": "professional",
      "categoryLabelEn": "Professional Services",
      "categoryLabelKm": "សេវាកម្មវិជ្ជាជីវៈ",
      "imagePath": "portfolio/hr-creative/hr-creative-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "HR Creative logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ HR Creative",
      "descriptionEn": "Logo design project for HR Creative in the Professional Services category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ HR Creative ក្នុងប្រភេទសេវាកម្មវិជ្ជាជីវៈ។",
      "displayOrder": 50,
      "featured": false
    },
    {
      "id": "portfolio-dina-garage",
      "slug": "dina-garage",
      "brandName": "យានដ្ឋាន ឌីណា",
      "businessCategory": "auto",
      "categoryLabelEn": "Auto & Vehicle",
      "categoryLabelKm": "យានយន្ត",
      "imagePath": "portfolio/dina-garage/dina-garage-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "យានដ្ឋាន ឌីណា logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ យានដ្ឋាន ឌីណា",
      "descriptionEn": "Logo design project for យានដ្ឋាន ឌីណា in the Auto & Vehicle category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ យានដ្ឋាន ឌីណា ក្នុងប្រភេទយានយន្ត។",
      "displayOrder": 51,
      "featured": false
    },
    {
      "id": "portfolio-cafe-village",
      "slug": "cafe-village",
      "brandName": "Cafe Village",
      "businessCategory": "food",
      "categoryLabelEn": "Food & Beverage",
      "categoryLabelKm": "អាហារ និងភេសជ្ជៈ",
      "imagePath": "portfolio/cafe-village/cafe-village-portfolio.jpg",
      "imageWidth": 1600,
      "imageHeight": 1143,
      "altTextEn": "Cafe Village logo portfolio image",
      "altTextKm": "រូបភាពស្នាដៃឡូហ្គោ Cafe Village",
      "descriptionEn": "Logo design project for Cafe Village in the Food & Beverage category.",
      "descriptionKm": "គម្រោងរចនាឡូហ្គោសម្រាប់ Cafe Village ក្នុងប្រភេទអាហារ និងភេសជ្ជៈ។",
      "displayOrder": 52,
      "featured": false
    }
  ]
};
